name: Setup C++ build environment
description: Installs uv, xmake, and LLVM

inputs:
  os:
    required: true
  plat:
    required: true
  arch:
    required: true
  build_type:
    required: true
  llvm_version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Free Disk Space
      if: inputs.os == 'Linux'
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Fetch tags
      shell: bash
      run: git submodule foreach --recursive 'git fetch --tags --depth=1'

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      with:
        # https://github.com/astral-sh/uv/tags
        version: 0.10.7
        enable-cache: true

    - name: Create xmake file if not exists
      shell: bash
      run: |
        if [[ ! -f "xmake.lua" ]]; then
          printf 'target("dummy_from_cxx_setup_action")\n  set_kind("binary")\n' > xmake.lua
        fi

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
      with:
        # https://github.com/xmake-io/xmake/tags
        xmake-version: 3.0.9
        actions-cache-folder: .xmake-cache
        actions-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-xmake
        package-cache: true
        package-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-packages
        build-cache: true
        build-cache-path: build/.build_cache
        build-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-${{ inputs.build_type }}-${{ inputs.llvm_version }}-build
        project-path: .

    - name: Install LLVM tools
      uses: pug523/install-llvm-action@233ad1a2ce9110f71dcf05c2cce4780bbeafd2f1
      with:
        # https://github.com/pug523/install-llvm-action/blob/master/assets.json
        version: ${{ inputs.llvm_version }}

    - name: Setup environment variables
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == "Linux" ]]; then
          echo "LD_LIBRARY_PATH=${{ env.LLVM_PATH }}/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "LDFLAGS=-L${{ env.LLVM_PATH }}/lib -Wl,-rpath,${{ env.LLVM_PATH }}/lib" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "macOS" ]]; then
          xcode-select --install || true
          SDK=$(xcrun --show-sdk-path)
          echo "SDKROOT=$SDK" >> $GITHUB_ENV
          echo "LDFLAGS=-L${{ env.LLVM_PATH }}/lib -fuse-ld=lld -Wl,-rpath,${{ env.LLVM_PATH }}/lib" >> $GITHUB_ENV
          echo "CXXFLAGS=-isysroot $SDK" >> $GITHUB_ENV
          echo "${{ env.LLVM_PATH }}/bin" >> $GITHUB_PATH
        # elif [[ "${{ inputs.os }}" == "Windows" ]]; then
        #   # We don't use libc++ in Windows currently so currently commented out.
        #   echo "${{ env.LLVM_PATH }}/bin" >> $GITHUB_PATH
        #   echo "${{ env.LLVM_PATH }}/lib" >> $GITHUB_PATH
        fi
