name: "Setup GN"
description: "Builds, installs, and caches GN"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
      with:
        # https://github.com/astral-sh/uv/tags
        version: 0.11.32
        enable-cache: true

    - name: Initialize MSVC Developer Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

    - name: Check out GN source
      shell: bash
      run: |
        SRC_DIR="$RUNNER_TEMP/gn-src"

        if [ ! -d "$SRC_DIR/.git" ]; then
          git clone --depth 1 https://gn.googlesource.com/gn "$SRC_DIR"
        fi

    - name: Get GN revision
      id: gn-revision
      shell: bash
      run: |
        cd "$RUNNER_TEMP/gn-src"
        echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Cache GN binary
      id: cache-gn
      uses: actions/cache@3edfce9056124e459a23f683a21433670d47daca
      with:
        path: ${{ runner.temp }}/gn-bin
        key: ${{ runner.os }}-gn-bin-${{ steps.gn-revision.outputs.sha }}

    - name: Build GN (Linux / macOS)
      if: steps.cache-gn.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        GN_SRC="$RUNNER_TEMP/gn-src"
        GN_BIN="$RUNNER_TEMP/gn-bin"

        mkdir -p "$GN_BIN"

        cd "$GN_SRC"
        uv run build/gen.py --allow-warning
        ninja -C out gn

        cp out/gn "$GN_BIN/gn"

    - name: Build GN (Windows)
      if: steps.cache-gn.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: cmd
      run: |
        if not exist "%RUNNER_TEMP%\gn-bin" mkdir "%RUNNER_TEMP%\gn-bin"

        cd /d "%RUNNER_TEMP%\gn-src"
        uv run build/gen.py --allow-warning
        ninja -C out gn.exe

        copy /Y "out\gn.exe" "%RUNNER_TEMP%\gn-bin\gn.exe"

    - name: Setup environment variables
      shell: bash
      run: |
        echo "$RUNNER_TEMP/gn-bin" >> "$GITHUB_PATH"
