name: "Setup GN"
description: "Builds, installs, and caches GN"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@66fcabf4d07f2b61e164d83ccd6829fcda36ae0f
      with:
        python-version: '3.14'

    - name: Initialize MSVC Developer Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

    - name: Check out GN source
      shell: bash
      run: |
        if [ ! -d "gn" ]; then
          git clone https://gn.googlesource.com/gn gn
        fi

    - name: Cache GN build output
      id: cache-gn
      uses: actions/cache@3edfce9056124e459a23f683a21433670d47daca
      with:
        path: gn/out
        key: ${{ runner.os }}-gn-${{ hashFiles('gn/build/**', 'gn/tools/**') }}
        restore-keys: |
          ${{ runner.os }}-gn-

    - name: Build GN (Linux / macOS)
      if: steps.cache-gn.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        cd gn
        python3 build/gen.py --allow-warning
        ninja -C out gn

    - name: Build GN (Windows)
      if: steps.cache-gn.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: cmd
      run: |
        cd gn
        python build/gen.py --allow-warning
        ninja -C out gn.exe

    - name: Setup environment variables
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/gn/out" >> $GITHUB_PATH
