version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/cxx-setup"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/cxx-gn-setup"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/setup-gn"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

