name: Setup C++ GN build environment
description: Installs uv, ninja, gn, and LLVM

inputs:
  os:
    required: true
  llvm_version:
    required: true
  directory:
    description: "Directory to install LLVM and Clang binaries to. Defaults to the action default (workspace ./llvm)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup base environment
      uses: pug523/actions/cxx-base-setup@main
      with:
        os: ${{ inputs.os }}
        llvm_version: ${{ inputs.llvm_version }}
        directory: ${{ inputs.directory }}

    - name: Setup gn
      uses: pug523/actions/setup-gn@main
