name: Setup C++ xmake build environment
description: Installs uv, xmake, and LLVM

inputs:
  os:
    required: true
  plat:
    required: true
  arch:
    required: true
  build_type:
    required: true
  llvm_version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup base environment
      uses: pug523/actions/cxx-base-setup@main
      with:
        os: ${{ inputs.os }}
        llvm_version: ${{ inputs.llvm_version }}

    - name: Create xmake file if not exists
      shell: bash
      run: |
        if [[ ! -f "xmake.lua" ]]; then
          printf 'target("dummy_from_cxx_setup_action")\n  set_kind("binary")\n' > xmake.lua
        fi

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
      with:
        # https://github.com/xmake-io/xmake/tags
        xmake-version: 3.1.0
        actions-cache-folder: .xmake-cache
        actions-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-xmake
        package-cache: true
        package-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-packages
        build-cache: true
        build-cache-path: build/.build_cache
        build-cache-key: ${{ inputs.os }}-${{ inputs.plat }}-${{ inputs.arch }}-${{ inputs.build_type }}-${{ inputs.llvm_version }}-build
        project-path: .
