name: Test cxx-xmake-setup Composite Action

on:
  push:
    branches: [ main ]
    paths: &ci_paths
      - cxx-xmake-setup/**
      - cxx-base-setup/**
      - .github/workflows/test-cxx-xmake-setup.yaml
  pull_request:
    branches: [ main ]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  test-cxx-xmake-setup:
    name: Test xmake on ${{ matrix.os-name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner-os: ubuntu-latest
            os-name: Linux
            plat: linux
            arch: x86_64
            llvm-version: "22.1.8"
          - runner-os: macos-latest
            os-name: macOS
            plat: macos
            arch: x86_64
            llvm-version: "22.1.8"
          - runner-os: windows-latest
            os-name: Windows
            plat: windows
            arch: x64
            llvm-version: "22.1.8"

    runs-on: ${{ matrix.runner-os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive

      - name: Run cxx-xmake-setup action
        uses: ./cxx-xmake-setup
        with:
          os: ${{ matrix.os-name }}
          plat: ${{ matrix.plat }}
          arch: ${{ matrix.arch }}
          build_type: release
          llvm_version: ${{ matrix.llvm-version }}

      - name: Verify xmake installation
        shell: bash
        run: |
          which xmake || type xmake
          xmake --version
