name: Test cxx-base-setup Composite Action

on:
  push:
    branches: [ main ]
    paths: &ci_paths
      - cxx-base-setup/**
      - .github/workflows/test-cxx-base-setup.yaml
  pull_request:
    branches: [ main ]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  test-cxx-base-setup:
    name: Test Base on ${{ matrix.os-name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner-os: ubuntu-latest
            os-name: Linux
            llvm-version: "22.1.8"
          - runner-os: macos-latest
            os-name: macOS
            llvm-version: "22.1.8"
          - runner-os: windows-latest
            os-name: Windows
            llvm-version: "22.1.8"

    runs-on: ${{ matrix.runner-os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive

      - name: Run cxx-base-setup action
        uses: ./cxx-base-setup
        with:
          os: ${{ matrix.os-name }}
          llvm_version: ${{ matrix.llvm-version }}

      - name: Verify uv installation
        shell: bash
        run: |
          which uv || type uv
          uv --version

      - name: Verify LLVM binaries
        shell: bash
        run: |
          echo "LLVM_PATH is: $LLVM_PATH"
          TOOLS=("clang" "clang++")
          if [[ "${{ matrix.os-name }}" == "Linux" ]]; then
            TOOLS+=("ld.lld")
          elif [[ "${{ matrix.os-name }}" == "macOS" ]]; then
            TOOLS+=("ld64.lld")
          elif [[ "${{ matrix.os-name }}" == "Windows" ]]; then
            TOOLS+=("lld-link" "clang-cl")
          fi

          for tool in "${TOOLS[@]}"; do
            echo "Testing tool: $tool"
            $tool --version
          done

      - name: Test C++ Compilation & libc++ Linkage
        shell: bash
        run: |
          cat << 'EOF' > test_main.cpp
          #include <iostream>
          #include <vector>
          #include <string>

          int main() {
              std::vector<std::string> msg {"Hello", "from", "C++", "Toolchain!"};
              for (const auto& word : msg) {
                  std::cout << word << " ";
              }
              std::cout << std::endl;
              return 0;
          }
          EOF

          if [[ "${{ matrix.os-name }}" == "Linux" ]]; then
            clang++ -std=c++20 -stdlib=libc++ test_main.cpp -o test_app -lc++ -lc++abi $LDFLAGS
            ./test_app
            ldd test_app | grep -i "libc++" || (echo "libc++ is not linked!" && exit 1)
          elif [[ "${{ matrix.os-name }}" == "macOS" ]]; then
            clang++ -std=c++20 test_main.cpp -o test_app $CXXFLAGS $LDFLAGS
            ./test_app
            otool -L test_app
          elif [[ "${{ matrix.os-name }}" == "Windows" ]]; then
            clang++ -std=c++20 test_main.cpp -o test_app.exe
            ./test_app.exe
          fi
