name: Test cxx-gn-setup Composite Action

on:
  push:
    branches: [ main ]
    paths: &ci_paths
      - cxx-gn-setup/**
      - cxx-base-setup/**
      - setup-gn/**
      - .github/workflows/test-cxx-gn-setup.yaml
  pull_request:
    branches: [ main ]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  test-cxx-gn-setup:
    name: Test GN on ${{ matrix.os-name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner-os: ubuntu-latest
            os-name: Linux
            plat: linux
            arch: x86_64
            llvm-version: "23.1.2"
          - runner-os: macos-latest
            os-name: macOS
            plat: macos
            arch: x86_64
            llvm-version: "23.1.2"
          - runner-os: windows-latest
            os-name: Windows
            plat: windows
            arch: x64
            llvm-version: "23.1.2"

    runs-on: ${{ matrix.runner-os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive

      - name: Run cxx-gn-setup action
        uses: ./cxx-gn-setup
        with:
          os: ${{ matrix.os-name }}
          llvm_version: ${{ matrix.llvm-version }}

      - name: Verify gn installation
        shell: bash
        run: |
          which gn || type gn
          gn --version
